# Generated by Django 5.0.6 on 2024-06-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachemnts/'),
        ),
        migrations.AddField(
            model_name='reply',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachemnts/'),
        ),
    ]
